### ISSUE TITLE
Getting an error when running the prediction script for detection

### ISSUE THREAD

**Issue by Preyansh17** [luoda888/2021-DIGIX-BASELINE#2]
make: Entering directory '/content/drive/MyDrive/menu_data/checkpoints/detector/postprocess'
make: 'simple_dilate.so' is up to date.
make: Leaving directory '/content/drive/MyDrive/menu_data/checkpoints/detector/postprocess'
Traceback (most recent call last):
  File "detector/predict.py", line 22, in <module>
    from detector.postprocess import simple_dilate
  File "/content/drive/MyDrive/menu_data/checkpoints/detector/postprocess/__init__.py", line 11, in <module>
    from .simple_dilate import simple_dilate as csimple_dilate
ImportError: libopencv_dnn.so.3.4: cannot open shared object file: No such file or directory.

I installed opencv3.4.2 also but still doesn't work

**Comment by JasonCZH4** [comment]
Have you solved it?I meet the similar problem.
Here is the Error Info:
mingw32-make: Entering directory 'C:/Users/ASUS/PycharmProjects/AI_Image/DIGIX_5/baseline-game5/checkpoints/detector/postprocess'
mingw32-make: 'simple_dilate.so' is up to date.
mingw32-make: Leaving directory 'C:/Users/ASUS/PycharmProjects/AI_Image/DIGIX_5/baseline-game5/checkpoints/detector/postprocess'
Traceback (most recent call last):
  File "C:/Users/ASUS/PycharmProjects/AI_Image/DIGIX_5/baseline-game5/checkpoints/detector/postprocess/__init__.py", line 11, in <module>
    from .simple_dilate_ import simple_dilate as csimple_dilate
ImportError: attempted relative import with no known parent package

**Comment by Preyansh17** [comment]
@JasonCZH4  no I have not been able to solve this issue yet.
